import type { SpaceInput } from './space';
export function roomVisual(input:SpaceInput){
 if(input.roomStyle==='vintage')return {key:'vintage' as const,file:'yumin-vintage-developer-v2',alt:'원목 침대와 네이비 체크 침구, 개발 작업 책상이 있는 빈티지 개인 방',meaning:'원목과 체크 침구로 익숙한 휴식의 자리를 만들고 개발 작업대와 침대의 역할을 나눈다. 바다 액자는 수의 유연함, 금속 작업 조명은 금의 정돈을 상징하는 디자인 후보다. 원국 개수만으로 용신이나 실제 효과를 확정하지 않는다. 사진의 바다 전망은 콘셉트이며 사용자의 실제 창밖이 아니다.',names:{art:'시선을 쉬게 하는 원목 수평선 액자',light:'작업의 경계를 밝혀주는 금속 조명',plant:'원목 수납장 위 초록 화분',fabric:'네이비 코튼과 버건디 체크 쿠션',tray:'하루의 소지품을 모으는 조개 트레이'}};
 if(input.roomStyle==='pastel')return {key:'pastel' as const,file:'yunji-pastel-loft-v1',alt:'밝은 원목과 말차·라벤더 체크, 포근한 소파를 둔 파스텔 복층 콘셉트',meaning:'밝은 원목, 말차와 라벤더 체크로 휴식과 일상을 구분한다. 두 곡선 액자는 서로의 여백을 지키며 가까워지는 관계의 상징, 오팔 조명은 표현의 온기, 트레이는 나를 돌보는 작은 습관으로 설명한다. 목과 화의 상징은 상담에서 선택한 보완 방향과 맞을 때만 연결한다. 복층은 참고 콘셉트이며 사용자의 실제 구조나 공사 제안이 아니다. shared이면 소파 대신 개인 방의 의자·침대 주변에 색과 소재를 적용한다.',names:{art:'서로의 여백을 담은 두 곡선 액자',light:'마음을 풀어주는 오팔 테이블 조명',plant:'소파 곁 작은 초록 화분',fabric:'말차와 라벤더 체크 쿠션',tray:'나를 위한 시간을 담는 세라믹 트레이'}};
 if(input.roomStyle==='gaming')return {key:'gaming' as const,file:'hyunwoo-gaming-room-v1',alt:'암막커튼과 듀얼 모니터 게임 책상, 따뜻한 간접 조명을 둔 차분한 방',meaning:'게임과 휴식의 자리를 구분하고 암막커튼과 속커튼으로 빛을 조절한다. 산과 새벽 액자는 흔들릴 때 돌아올 중심과 새로운 시작의 상징이다. 따뜻한 조명과 정리 트레이는 게임을 마친 뒤 쉬는 전환을 돕는다. 토·화의 상징은 상담에서 정한 보완 방향과 맞을 때만 연결하며 커리어 성공이나 집중력 향상을 보장하지 않는다.',names:{art:'다음 시작을 바라보는 산과 새벽 액자',light:'휴식의 시작을 알리는 오팔 조명',plant:'작업 공간 곁 초록 화분',fabric:'빛을 조절하는 차콜 암막커튼',tray:'컨트롤러와 헤드폰을 정돈하는 펠트 트레이'}};
 if(input.roomStyle==='coastal'&&input.layout!=='separate')return {key:'coastal' as const,file:'modern-vintage-bedroom-v1',alt:'월넛과 메탈 선반, 바다 액자와 초록 식물이 어우러진 모던 빈티지 개인 침실',names:{art:'다음 풍경을 여는 수평선 액자',light:'알루미늄과 버건디 작업 조명',plant:'메탈 선반 위 초록 식물',fabric:'화이트 코튼과 올리브 쿠션',tray:'크림 세라믹 조개 트레이'}};
 if(input.layout==='shared')return {key:'collector' as const,file:'collector-bedroom-v1',alt:'카드형 작품 보드와 실버 액자, 책상과 침대를 갖춘 가족 집 안의 개인 방',names:{art:'흐름을 담은 잉크블루 실버 액자',light:'크롬과 오팔 유리 테이블 조명',plant:'작은 초록 화분',fabric:'슬레이트 블루 쿠션과 리넨',tray:'옅은 블루 유리 트레이'}};
 if(input.layout==='separate')return {key:'separate' as const,file:'pearl-living',alt:'크림 소파와 은은한 푸른 패브릭이 있는 분리형 거실',names:{art:'맑은 블루 추상화 액자',light:'유리 구형 테이블 조명',plant:'작은 화분과 초록 잎',fabric:'블루그레이 패브릭',tray:'크림색 원형 트레이'}};
 return {key:'studio' as const,file:'warm-studio',alt:'원목과 따뜻한 빛이 있는 아늑한 원룸',names:{art:'차분한 곡선의 추상화 액자',light:'버건디 버섯 조명',plant:'가벼운 잎의 실내 나무',fabric:'살구빛 조개 쿠션',tray:'실버 오브제 트레이'}};
}
