import { dashboardReflection } from '@/lib/consultation/dashboard-reflection';
import { wantsNeighborhoods } from '@/lib/consultation/relocation';
import Image from 'next/image';
import type { Ref } from 'react';
import { ElementBead } from './ChartCard';
import type { Reply } from '@/lib/consultation/schema';
import type { Chart } from '@/lib/consultation/saju';
import type { SpaceDashboard, SpaceInput, NeighborhoodResearch } from '@/lib/consultation/space';
import { itemTraits } from '@/lib/consultation/item-traits';
import { roomVisual } from '@/lib/consultation/room-visual';
import { RoomDetail } from './RoomDetail';
import { neighborhoodMatch } from '@/lib/consultation/neighborhood-match';
import s from './JewelDashboard.module.css';

const properties={light:{title:'밤의 온기를 지키는 빛'},plant:{title:'다시 자라나는 작은 생기'},fabric:{title:'긴장을 내려놓는 부드러운 결'},art:{title:'매일 눈에 담는 나만의 기운'},tray:{title:'하루의 흩어짐을 모으는 자리'}};
function shop(query:string){return `https://search.shopping.naver.com/search/all?query=${encodeURIComponent(query)}`;}
export function JewelDashboard({dashboard,topic,input,research,summary,onEdit,resultRef}:{dashboard:SpaceDashboard;topic:string;input:SpaceInput;research?:NeighborhoodResearch|null;chart:Chart|null;summary:Reply['summary'];onEdit:()=>void;resultRef:Ref<HTMLElement>}){
 const match=neighborhoodMatch(research,dashboard.energy);
 const visual=roomVisual(input);
 const shownNames=visual.names;
 const journey=dashboard.journey;
 const context=summary?.desire??'';
 const intent=/돈|재물|수입|재정/.test(context)?'money':/연애|좋아하는|상대|호감/.test(context)?'love':/직장|커리어|취업/.test(context)?'career':topic;
 const nextScene=intent==='love'?'편안한 마음으로, 나다운 관계를 맞이하는 일상':intent==='career'?'애써 달린 하루 뒤, 내 속도로 다음을 준비하는 너':intent==='money'?'복잡한 생각을 정돈하고, 나의 기준으로 선택하는 너':'혼자 돌아온 밤에도, 마음 놓고 나답게 쉬는 너';
 const roomHeadline=intent==='love'?'관계를 소중히 여기는 너에게, 마음을 꺼낼 온기를 더해주는 공간':'하루를 애써 살아낸 너에게, 마음 놓고 쉴 여유를 돌려주는 공간';
 const reflection=dashboardReflection(intent);
 const strength=summary?.strength.split(/[.!?。]/)[0];
 const showNeighborhoods=wantsNeighborhoods(input,topic);
 const alternatives=showNeighborhoods?(dashboard.alternatives??[]):[];
 const unorderedObjects=dashboard.objects.some(o=>o.kind==='art')?dashboard.objects:[...dashboard.objects,{name:'나만의 기운을 담는 액자',kind:'art' as const,placement:'자주 머무는 자리에서 눈높이에 맞춰',reason:`${dashboard.energy.map(e=>e.element).join('·')}의 색과 형태를 일상에 담는 작은 장면이야. 너에게 필요한 흐름을 매일 눈에 담으며, 집 안에 마음 놓고 머물 시선의 자리를 만들어보자.`}];
 const objects=[...unorderedObjects].sort((a,b)=>Number(b.kind==='art')-Number(a.kind==='art'));
 return <section ref={resultRef} className={s.box} aria-label="나의 풍수 인테리어 대시보드">
  <header className={s.heading}><div><span>YOUR NEXT CHAPTER</span><h2>A little more<br/><b>you.</b></h2><p>네가 들려준 마음에서 시작된, 너를 위한 공간.</p></div><div className={s.chapterTags}><span>01 나의 흐름</span><span>02 공간과 아이템</span><span>03 나와 동네</span></div></header>
  <section className={s.evolution} aria-label="지금의 흐름과 기대하는 변화"><article className={s.before}><span className={s.eyebrow}>NOW · 함께 살펴볼 흐름</span><h3>{reflection.title}</h3><p>{reflection.body}</p></article><article className={s.after}><span className={s.eyebrow}>NEXT · 공간과 함께 기대하는 일상</span><h3>{nextScene}</h3><p>{journey?.bridge??'너를 위한 빛과 부드러운 촉감, 시선이 머무는 그림을 곁에 둘게. 이 공간이 하루를 버틴 너에게 편히 기댈 자리가 되어주도록.'}</p><div className={s.featureTags}>{(journey?.traits??['편안한 머무름','나를 위한 여유','생활의 중심']).map(t=><span key={t}>{t}</span>)}</div></article></section>
  <figure className={s.room}><Image src={`/images/consultation/jewels/${visual.file}.png`} alt={visual.alt} width={1536} height={1024} priority sizes="(max-width:760px) 95vw, 1100px"/><figcaption className={s.photoCaption}><div><span>FOR THE WAY YOU ARE</span><h3>{journey?.headline??roomHeadline}</h3></div></figcaption></figure>
  <div className={s.roomNote}><p>취향과 생활 조건을 참고한 AI 인테리어 콘셉트 · 실제 방 구조와는 다를 수 있어요.</p></div>
  <section className={s.why}><span className={s.eyebrow}>WHY IT FITS YOU</span><h3>너의 좋은 점은 그대로.<br/>버거운 부분은 공간이 받쳐주도록.</h3>{strength&&<p className={s.strength}>{strength}.</p>}<p className={s.reason}>{dashboard.intro}</p><div className={s.energyCards}>{dashboard.energy.map(e=><article key={e.element}><ElementBead element={e.element}/><span>{e.element} · 함께 채울 기운</span><p>{e.meaning}</p></article>)}</div><div className={s.practical}><article><h4>{dashboard.desk.title}</h4><p>{dashboard.desk.body}</p></article><article><h4>{dashboard.view.title}</h4><p>{dashboard.view.body}</p></article></div></section>
  <section id="space-items" className={s.objectSection}><div className={s.sectionHeading}><span>02 · ITEMS FOR YOUR NEXT CHAPTER</span><h3>너의 일상을 받쳐줄 작은 아이템.</h3><p>색과 소재, 오행의 상징, 공간에서 하는 역할을 살펴봐.</p></div><div className={s.objectGrid}>{objects.map(object=>{const prop=properties[object.kind];const traits=itemTraits(visual.key,object.kind);return <article key={object.name} className={s.objectCard}><RoomDetail visual={visual} kind={object.kind} name={shownNames[object.kind]}/><div className={s.objectCopy}><span>{object.kind==='art'?'YOUR PERSONAL ART':'SPACE ITEM'} · 위 공간에서 찾은 디테일</span><h4>{prop.title}</h4><strong>{shownNames[object.kind]}</strong><dl className={s.itemTraits}><div><dt>색 · 소재</dt><dd>{traits.material}</dd></div><div><dt>오행 상징</dt><dd className={s.itemElements}>{traits.elements.map(({element,meaning})=><span key={element}><ElementBead element={element}/><b>{element}</b> · {meaning}</span>)}</dd></div><div><dt>공간 역할</dt><dd>{traits.role}</dd></div></dl><p>{object.placement}</p><p className={s.itemEffect}>{object.reason}</p>{object.kind==='art'&&<p>액자는 필요한 색과 형태를 한 장에 담는 방법이야. 앞으로 너만의 그림을 만들 때도 이 기운을 담아, 집에서도 배경화면에서도 곁에 둘 수 있어.</p>}<div className={s.itemActions}><a className={s.shopLink} href={shop(shownNames[object.kind])} target="_blank" rel="noreferrer">이런 특성의 제품 찾아보기</a><small>쇼핑 검색으로 연결 · 이미지와 동일한 판매 상품은 아니에요.</small></div></div></article>})}</div></section>
  <section className={`${s.glass} ${s.palette}`}><div><span className={s.eyebrow}>YOUR MATERIAL PALETTE</span><h3>나랑 어울리는 소재와 이유</h3></div><div className={s.swatches}>{dashboard.materials.map(m=><div key={m.name}><i data-color={m.color}/><strong>{m.name}</strong><p>{m.reason}</p></div>)}</div></section>
  <section className={`${s.glass} ${s.match}`}><span className={s.eyebrow}>03 · YOU & YOUR NEIGHBORHOOD</span><h3>나 × {input.neighborhood||'내 동네'}</h3><div className={s.scoreJewel}><div className={s.scoreCore}><strong>{match?.score??'—'}</strong><span>{match?`${match.score>=85?'상':match.score>=75?'중상':'보완하며 머무는 곳'} · 채운 해석 / 100`:'동네 정보가 더 필요해'}</span></div></div><p className={s.matchCaption}>너의 기운이 이 동네를 만났을 때.</p><div className={s.featureTags}>{match?.features.map(f=><span key={f.element} data-match={f.matched}><ElementBead element={f.element}/>{f.label} · {f.matched?'보완과 연결':'함께 살필 환경'}</span>)}</div><div className={s.balance}><article><span>GOOD FOR YOU</span><h4>나에게 좋은 점</h4>{dashboard.neighborhoodBalance?<><strong>{dashboard.neighborhoodBalance.good.title}</strong><p>{dashboard.neighborhoodBalance.good.body}</p></>:<><strong>{match?.features.filter(f=>f.matched).map(f=>f.label).join(' · ')||'알려준 환경에서 찾아가는 균형'}</strong><p>{match?.features.some(f=>f.matched)?`${match.features.filter(f=>f.matched).map(f=>f.element).join('·')}의 상징과 연결되는 환경이 있어. ${dashboard.energy.filter(e=>match.features.some(f=>f.matched&&f.element===e.element)).map(e=>e.meaning).join(' ')}`:'아직 확인된 환경이 충분하지 않아. 네가 알려준 풍경과 채광을 먼저 중심에 둘게.'}</p></>}</article><article><span>ROOM TO BALANCE</span><h4>보완하면 좋을 점</h4>{dashboard.neighborhoodBalance?<><strong>{dashboard.neighborhoodBalance.caution.title}</strong><p>{dashboard.neighborhoodBalance.caution.body}</p></>:<><strong>동네 밖의 흐름을, 내 방 안의 여유로</strong><p>{dashboard.energy.filter(e=>!match?.features.some(f=>f.matched&&f.element===e.element)).map(e=>`${e.element}의 보완은 아직 동네 정보에서 충분히 연결되지 않았어. ${e.meaning}`).join(' ')||'주변 환경이 잘 맞더라도 집 안의 빛과 시선까지 대신 채워주지는 않아. 알려준 방 조건에 맞춰 편안한 머무름을 더해보자.'}</p><small>정보에 연결되지 않은 기운이 실제로 없는 것은 아니야.</small></>}</article></div><div className={s.neighborhoodStory}><h4>{dashboard.neighborhood.title}</h4><p>{dashboard.neighborhood.body}</p><p><b>집 안에서 이어갈 균형</b> · {journey?.bridge??dashboard.energy.map(e=>e.meaning).join(' ')}</p></div>{showNeighborhoods&&<section aria-label="이사·자취를 위한 동네 추천"><h3>다음에 살아보고 싶은 동네</h3><p>이사·자취를 생각하는 너를 위한 후보야. 실제 통근 시간과 주거비, 출입 보안은 따로 확인해봐.</p>{!alternatives.length&&<p>아직 확인된 추천 후보가 없어. 동네·방 정보를 수정하고 다시 추천받을 수 있어.</p>}<div className={s.alternatives}>{alternatives.map(place=><article key={place.name}><span className={s.eyebrow}>{place.scope} · 다음에 살아보고 싶은 곳</span><h4>{place.name}</h4><p>{place.reason}</p><div className={s.featureTags}>{place.traits.map(t=><span key={t}>{t}</span>)}</div><a href={place.sourceUrl} target="_blank" rel="noreferrer">동네 환경 살펴보기</a></article>)}</div></section>}<div className={s.sources}>{research?.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title}</a>)}</div><p className={s.method}>환경 정보에 오행의 상징을 연결한 채운의 해석이에요.{match&&` 기본 50 + 보완 기운과 연결된 비율 × 40 (${match.matched}/${match.total}).`} 실제 주거 성능이나 미래의 행복을 측정하는 점수는 아니에요.</p></section>
  <button className={s.edit} onClick={onEdit}>동네·방 정보 바꾸고 다시 추천받기</button>
 </section>;
}
